<script setup lang="ts">
import { onMounted, onUnmounted } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { getCurrentWindow } from "@tauri-apps/api/window";
import type { UnlistenFn } from "@tauri-apps/api/event";
import { toast } from "vue-sonner";
import { Toaster } from "@/components/ui/sonner";
import TitleBar from "@/components/TitleBar.vue";
import BatchProgressFloat from "@/components/report/BatchProgressFloat.vue";
import { onListen } from "@/lib/tauri";
import { useStreamMarkdownWheelZoom } from "@/composables/useStreamMarkdownWheelZoom";
import { usePinsStore } from "@/stores/pins";
import { useBackgroundTasksStore } from "@/stores/background-tasks";
import { useProjectsStore } from "@/stores/projects";
import { useSettingsStore } from "@/stores/settings";
import { useTagsStore } from "@/stores/tags";
import { useUpdateStore } from "@/stores/update";
import { useWikiStore } from "@/stores/wiki";
import type {
  BackgroundTaskProgressPayload,
  ConflictResolutionFinishedPayload,
  GitProjectChangedPayload,
  ReportGeneratedPayload,
} from "@/types";

const router = useRouter();
const { t } = useI18n();
const store = useProjectsStore();
const pinsStore = usePinsStore();
const tagsStore = useTagsStore();
const settingsStore = useSettingsStore();
const updateStore = useUpdateStore();
const wikiStore = useWikiStore();
const backgroundTasksStore = useBackgroundTasksStore();

// 托盘迷你弹窗窗口:仅加载主题/语言与项目列表,跳过标题栏、更新检查等主窗口专属逻辑
const isTrayPopup = getCurrentWindow().label === "tray-popup";

// markdown 全屏弹窗(teleport 到 body)内直接滚轮缩放 mermaid/图片,无需 ctrl
useStreamMarkdownWheelZoom();

let unlistenGit: UnlistenFn | undefined;
let unlistenBackgroundTasks: UnlistenFn | undefined;
let unlistenConflictResolution: UnlistenFn | undefined;

onMounted(async () => {
  // 托盘弹窗窗口已开 OS 级透明,body 不再刷底色,让玻璃皮肤能透出桌面
  if (isTrayPopup) {
    document.body.classList.add("tray-popup-window");
  }
  await settingsStore.init();
  if (!isTrayPopup) {
    updateStore.init();
    // 启动后静默检查更新(dev 环境跳过,避免无签名产物时无意义报错)
    if (settingsStore.autoCheckUpdate && !import.meta.env.DEV) {
      updateStore.checkForUpdate(false);
    }
  }
  if (!isTrayPopup) {
    unlistenBackgroundTasks = await onListen<BackgroundTaskProgressPayload>(
      "background://task-progress",
      (payload) => backgroundTasksStore.applyProgress(payload),
    );
    unlistenConflictResolution = await onListen<ConflictResolutionFinishedPayload>(
      "agent://conflict-resolution-finished",
      (payload) => {
        if (payload.success) {
          toast.success(t("git.conflict.agentResolved"));
        } else if (payload.error) {
          toast.error(t("git.conflict.agentFailed", { error: payload.error }));
        } else {
          toast.warning(t("git.conflict.agentIncomplete", { count: payload.remaining.length }));
        }
      },
    );
    // 先订阅再拉取首批状态,避免启动阶段后台检查事件先于监听器到达。
    unlistenGit = await onListen<GitProjectChangedPayload>("git://project-changed", (payload) => {
      store.applyGitProjectEvent(payload);
      if (!payload.head_changed) return;
      if (payload.project_id == null) return;
      if (!settingsStore.wikiAutoUpdate && !payload.wiki_auto_update) return;
      const name = payload.name ?? payload.path;
      wikiStore
        .autoUpdate({ id: payload.project_id, path: payload.path, name }, settingsStore.language)
        .then((count) => {
          if (count > 0) {
            toast.success(t("wiki.autoUpdated", { name, count }));
          }
        })
        .catch((e) => {
          toast.error(t("wiki.autoUpdateFailed", { name, error: String(e) }));
        });
    });
  }
  store.fetchProjects({ withGit: !isTrayPopup });
  pinsStore.fetchPins();
  // 另一窗口(托盘弹窗/主窗口)切换收藏后同步刷新;保留已有 git 状态避免闪烁
  onListen("projects://favorite-changed", () => {
    store.fetchProjects({ withGit: false });
  });
  // 另一窗口变更「常用命令」标记后同步刷新
  onListen("projects://pins-changed", () => {
    pinsStore.fetchPins();
  });
  // 另一窗口变更主题/皮肤/MD 主题后同步当前窗口的 DOM(主要是托盘弹窗跟随主窗口)
  // 托盘窗口仅在 init 时从 settings.json 读一次主题,期间切换需要靠广播同步。
  // 广播带全量最新值,接收方先覆盖自己的 ref(各 webview 的 Pinia store 互相独立)再 apply,
  // 否则 applyTheme 用的是本地 ref,等于用旧值覆盖,主题不会变
  onListen<{ theme: string; themeSkin: string; mdTheme: string }>(
    "settings://theme-changed",
    (payload) => {
      settingsStore.syncThemeFromExternal(payload);
    },
  );
  // 另一窗口变更打开方式(自定义项/排序/默认项)后同步当前窗口(托盘弹窗菜单与主窗口设置页保持一致)
  onListen<{ customOpenWith: unknown; order: unknown; defaultOpenWith: unknown }>(
    "settings://open-with-changed",
    (payload) => {
      settingsStore.syncOpenWithFromExternal(payload);
    },
  );
  if (isTrayPopup) return;
  tagsStore.fetchTags();
  onListen<ReportGeneratedPayload>("report://generated", (payload) => {
    // 手动/批量生成的 scheduleName 为空:单条生成在对话框内展示结果,
    // 批量有右下角浮窗与完成 toast,这里只提示定时任务自动生成的报告
    if (!payload.scheduleName) return;
    toast.success(
      t("reportSchedule.autoGenerated", {
        scheduleName: payload.scheduleName,
        dateFrom: payload.dateFrom,
      }),
      {
        action: {
          label: t("common.view"),
          onClick: () => router.push("/report-history"),
        },
      },
    );
  });
  // 托盘弹窗/菜单请求跳转到项目详情页
  onListen<{ projectId: number }>("main://navigate", async (payload) => {
    // 主窗口 store 可能正被搜索/标签筛选裁剪;若列表里没该项目,
    // 单点拉取并注入后再跳转,避免详情页误报「项目不存在或已被删除」。
    // 后端 get_project 抛出 project_not_found 时跳过注入,详情页会显示 not-found。
    if (!store.projects.some((p) => p.id === payload.projectId)) {
      try {
        await store.ensureProjectLoaded(payload.projectId);
      } catch {
        /* 项目真实不存在:仍跳转,详情页会显示 not-found 状态 */
      }
    }
    router.push(`/projects/${payload.projectId}`);
  });
});

onUnmounted(() => {
  unlistenGit?.();
  unlistenBackgroundTasks?.();
  unlistenConflictResolution?.();
});
</script>

<template>
  <!-- 托盘弹窗窗口:整体透明,背景交给 TrayPopup 根节点(玻璃皮肤下透出系统模糊) -->
  <main
    class="flex h-screen flex-col overflow-hidden text-foreground"
    :class="isTrayPopup ? 'bg-transparent' : 'bg-background'"
  >
    <TitleBar v-if="!isTrayPopup" />
    <div class="min-h-0 flex-1">
      <router-view />
    </div>
  </main>
  <Toaster position="bottom-right" />
  <BatchProgressFloat v-if="!isTrayPopup" />
</template>
